export const timeline = [
  {
    company: "HeySago",
    location: "San Francisco, CA",
    title: "Software Development Engineer",
    date: "Apr 2026 — Present",
    type: "Full-time",
    description:
      "Built Python microservices on GKE for agentic workflows, ETL orchestration, API integrations, and financial data processing.",
    responsibilities: [
      "Built Python microservices on GKE for agentic workflows, ETL orchestration, API integrations, and financial data processing.",
      "Developed a financial insights software using RAG and Gemini to extract structured insights from raw financial news content.",
    ],
    stack: [
      "Python",
      "FastAPI",
      "PostgreSQL",
      "Elasticsearch",
      "MCP",
      "RAG",
      "GKE",
      "GCP",
      "Kubernetes",
      "LLMs",
      "Gemini API",
      "Auth0",
    ],
  },
  {
    company: "UVA Darden School of Business",
    location: "Charlottesville, VA",
    title: "Data Engineering Research Assistant",
    date: "Aug 2025 — Mar 2026",
    type: "Research",
    description:
      "Architected fault-tolerant data systems and AI-powered tooling to support faculty research at scale.",
    responsibilities: [
      "Architected fault-tolerant distributed ingestion systems processing 10TB+ of raw data and improving overall pipeline performance by ~70%.",
      "Built robust ingestion and web scraping infrastructure to collect millions of structured and unstructured financial records.",
      "Developed AI agents using RAG, vector databases, and OpenAI APIs to automate insight extraction from unstructured datasets.",
    ],
    stack: [
      "Python",
      "Machine Learning",
      "HPC",
      "SLURM",
      "Databricks",
      "Distributed Systems",
      "LLMs",
      "OpenAI API",
      "Vector DBs",
    ],
  },
  {
    company: "Rhombus Power Inc.",
    location: "Palo Alto, CA",
    title: "Full Stack Development Summer Intern",
    date: "May 2025 — Aug 2025",
    type: "Internship",
    description:
      "Shipped full-stack features and data tooling across mission-critical applications.",
    responsibilities: [
      "Built a data pipeline to parse, predict, and generate GeoJSON outputs from active satellite feeds, reducing runtime by ~40%.",
      "Contributed across multiple full-stack apps end-to-end — improving performance, scalability, and security.",
      "Identified and resolved critical issues in production deployments, improving stability and reliability for clients.",
    ],
    stack: [
      "PHP",
      "CodeIgniter",
      "Node.js",
      "ReactJS",
      "Apache Airflow",
      "Docker",
      "S3",
      "Vault",
      "HPC",
      "SLURM",
      "JIRA",
    ],
  },
  {
    company: "UVA CS Department",
    location: "Charlottesville, VA",
    title: "Graduate Research Assistant",
    date: "Sep 2024 — Nov 2024",
    type: "Research",
    description:
      "Research in machine learning and systems security focused on threat detection.",
    responsibilities: [
      "Worked on threat detection and SIEM rulesets for Windows, generating datasets via SOCBED and AMIDES environments.",
      "Evaluated research-grade systems for ML-driven threat detection, applying security principles end-to-end.",
      "Replicated multiple papers via reverse engineering, demonstrating limitations of generic SIGMA rulesets.",
    ],
    stack: ["Python", "Machine Learning", "Security", "SIGMA", "SOCBED", "AMIDES"],
  },
  {
    company: "Lab Systems (I) Pvt. Ltd.",
    location: "India",
    title: "Founding Software Engineer",
    date: "Aug 2022 — Jul 2024",
    type: "Founding",
    description:
      "First engineer of the Karpuragaurai Development Wing — owned core platform development and the initial technology roadmap.",
    responsibilities: [
      "Architected and shipped scalable cryptocurrency forensics and disk forensics applications from a blank slate.",
      "Built UI and REST APIs in C++ kernels and Python, improving software performance by ~70% via distributed processing.",
      "Developed AI-driven forensic agents to automate evidence analysis, anomaly detection, and investigation workflows.",
      "Led a product development team to optimize algorithms and architecture for diverse client deployments.",
      "Streamlined deployment and testing automation by implementing DevOps, optimizing cloud and on-prem container infrastructure.",
    ],
    stack: [
      "Blockchain",
      "NextJS",
      "Python",
      "C++",
      "Flask",
      "Electron",
      "pgVector",
      "vLLM",
      "AWS",
      "Cloudflare",
      "SQL / NoSQL",
    ],
  },
  {
    company: "Amazon Web Services (SLRTCE)",
    location: "Remote",
    title: "Cloud Intern",
    date: "Jun 2022 — Jul 2022",
    type: "Internship",
    description:
      "Hands-on training internship deploying end-to-end solutions on AWS.",
    responsibilities: [
      "Completed a structured training program building production-grade solutions on AWS Cloud.",
      "Deployed services using CloudFront, Amplify, IAM, WAF, EC2, CI/CD, Lambda, S3, RDS, and DynamoDB.",
    ],
    stack: ["AWS", "CloudFront", "Lambda", "S3", "EC2", "RDS", "DynamoDB", "IAM", "WAF", "CI/CD"],
  },
];
